name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"

      - name: Install packages
        run: npm ci

      - name: Run prettier
        run: npm run prettier

      - name: Run lints
        run: npm run lint

      - name: Run tests
        run: npm run test
